---

- name: Get device uptime
  hosts: LAB_GNS3
  connection: local
  gather_facts: no
   
  tasks:
  
  - name: "Task 1: run show version and check to see if output contains IOS"
    ios_command:
      commands: "show version"
      wait_for: result[0] contains IOS

      provider:
        host: "{{ # }}"
        username: "{{ # }}"
        password: "{{ # }}"
        timeout: 30
        
    register: version
 
  - name: "Task 2: display version output" 
    debug:
      msg: "{{ version }}"
    